### ISSUE TITLE
性能测试对比的问题

### ISSUE THREAD

**Issue by gehill** [netease-im/camellia#1]
我这儿想使用redis的proxy，就分别对camellia-redis-proxy、bilibili-overlord和predixy进行了性能测试对比

配置和这里介绍的一样 
https://github.com/netease-im/camellia/blob/master/camellia-redis-proxy/performance-report-1.md

camellia-redis-proxy用的是async模式，用1.0.5版本编译的。可是性能测试结果和您这儿的结果差距有点大。我这儿测试的camellia-redis-proxy对比bilibili-overlord和predixy差了一个数量级。比如单连接时测试get命令，camellia-redis-proxy的平均响应时间是1.5079，而bilibili-overlord和predixy分别是0.17和0.14

不知是不是我用的版本有问题？还是有什么调优的方式？

**Comment by caojiajun** [comment]
1、1.0.5版本没问题，云信线上目前就是1.0.5版本
2、camellia-redis-proxy的debug日志是不是没关？（samples中的logback.xml是开着debug日志的）
3、压测时长多久，1分钟，还是5分钟、10分钟
4、部署proxy、压测客户端的机器配置能否发一下
5、使用的java版本，以及JVM配置（包括堆、GC参数等）

**Comment by gehill** [comment]
确实，关了debug日志性能好了很多，camellia-redis-proxy性能提升到了0.3左右。不过比bilibili-overlord的0.17感觉还是低一点。
所有测试配置，无论overlord还是camellia-redis-proxy，我都是完全复制https://github.com/netease-im/camellia/blob/master/camellia-redis-proxy/performance-report-1.md这里的，包括jvm的启动配置。完全一模一样。jdk我用的jdk1.8.0_65
```sh
camellia-redis-proxy:
  type: async
  transpond:
    type: local
    local:
      type: simple
      resource: redis-cluster://***
```

```sh
-Xms4096m -Xmx4096m -XX:+UseG1GC
```

听您说云信线上用的这个版本，不知稳定性如何？我看了下源码，比如redis端主动断开连接，我看这边代码是stop连接，好像并未重连，不是否哪儿看漏了。不知道这个开源项目有没群之类的，能让我们跟着学习下的 ：）

**Comment by caojiajun** [comment]
1、不知道测试时间是多久，连续1分钟，还是5分钟、10分钟？测试平台是windows还是linux还是其他？
2、重连相关逻辑在RedisClientHub.java
3、云信线上目前还未出现过问题
4、加我微信吧：hdnxttl

**Comment by 904648702** [comment]
你好，想请教一下平均响应时间怎么是怎么测的？用redis-benchmark可以看到吗

**Comment by caojiajun** [comment]
欢迎查看最新的性能测试报告：
https://github.com/netease-im/camellia/blob/master/docs/redis-proxy/performance-report-8.md

这边是使用jedis编写客户端代码结合网易内部的压测平台做的测试

关于性能测试相关，如果有什么问题，可以加微信：hdnxttl

**Comment by caojiajun** [comment]
> 你好，想请教一下平均响应时间怎么是怎么测的？用redis-benchmark可以看到吗

redis-benchmark只能看tps
