### ISSUE TITLE
[Camellia Redis Proxy] windows prometheus scrape metrics error: strconv.ParseFloat: parsing "0\r"

### ISSUE THREAD

**Issue by yufenghui** [netease-im/camellia#101]
Module: [camellia-redis-proxy]
Version: [1.2.6]

Windows环境中启动prometheus监控端点，在Target中会出现 `strconv.ParseFloat: parsing "0\r"` 的报错。
根据报错信息，发现是\r换行符导致的问题。没有测试Linux环境，但估计是可以的。

通过设置下面的系统参数:
```java
System.setProperty("line.separator", "\n") ;
```

参数设置成功了，但是prometheus还是报错。翻了翻下面的代码，在这个`StatsPrometheusConverter.java`文件中。
```java
String totalFormat = "redis_proxy_total{type=\"%s\",} %d%n";
sb.append(String.format(totalFormat, "all", stats.getCount()));
```

String.format中的%n的取值不确定取的是哪个配置，貌似设置系统参数没有生效。尝试在本地覆盖框架配置如下：
```java
String totalFormat = "redis_proxy_total{type=\"%s\",} %d\n";
sb.append(String.format(totalFormat, "all", stats.getCount()));
```

将%n替换为\n就OK了。不确定是不是普现的问题。记录在此。

**Comment by caojiajun** [comment]
proxy和prometheus部署在不同的平台？

**Comment by yufenghui** [comment]
都在windows上，prometheus是docker desktop上启动的，proxy在idea中启动的。

**Comment by caojiajun** [comment]
看上去promethus是固定使用\n做换行符，而%n是根据平台使用不同的换行符。辛苦提个pr来fix这个问题吧

**Comment by yufenghui** [comment]
抱歉，最近比较忙。刚拉下代码，看到你已经改了。对了，忘记感谢开源这么好的项目。 @caojiajun
