### ISSUE TITLE
Redis sentinel password miss when create connection

### ISSUE THREAD

**Issue by segment11** [netease-im/camellia#114]
Module: camellia-redis-proxy
Version: 1.2.11
Content:
RedisSentinelUtils.getMasterAddr method need password parameter.

**Comment by caojiajun** [comment]
password of sentinel？

**Comment by caojiajun** [comment]
the password of sentinel and redis is different, 1.2.11 only support redis password

1.2.12 will support this feature

**Comment by segment11** [comment]
Ok, I get it. Thx.

**Comment by caojiajun** [comment]
v1.2.12 is released
