### ISSUE TITLE
redis cluster client connect error

### ISSUE THREAD

**Issue by lcwling** [netease-im/camellia#116]
Module: [camellia-redis-proxy]
Version: [v1.2.12]
Content: [redis cluster client connect error]

在使用redis 客户端工具（如：RedisDesktopManager、RESP），连接新版本V1.2.12的时候，出现这样的错误提示
无法加载数据库：
ERR DB index is out of range

**Comment by lcwling** [comment]
但是V1.2.0 版本连接正常

**Comment by caojiajun** [comment]
后端配置的是什么

**Comment by caojiajun** [comment]
看了一下变更记录，确实有行为变化
1.2.0时，select非0的database直接报错
1.2.1开始，支持select 非0的database，但是限制后端为非redis-cluster（当后端是redis-cluster时逻辑不合理，select 0也返回报错了）

1.2.13会修复这个问题

**Comment by caojiajun** [comment]
1.2.13 has released @lcwling

**Comment by lcwling** [comment]
Thanks！

**Comment by caojiajun** [comment]
可以加我微信拉进群，方便后续沟通哈
