### ISSUE TITLE
camellia-redis-proxy supprt `client list` command to get proxy client info

### ISSUE THREAD

**Issue by caojiajun** [netease-im/camellia#132]
Module: camellia-redis-proxy
Content: camellia-redis-proxy supprt `client list` command to get proxy client info

**Comment by caojiajun** [comment]
@InputOutputZ you can try `client info` and `client list` command in latest code

**Comment by InputOutputZ** [comment]
I can confirm it's working just perfectly, again, thanks so much for all your work.

<img width="810" alt="Screenshot 2023-08-22 at 13 20 48" src="https://github.com/netease-im/camellia/assets/4721398/2382c24d-75b9-4c92-ab59-0418e0c1f204">
