### ISSUE TITLE
camellia-redis-proxy frontend tls bidirectional authentication not effective

### ISSUE THREAD

**Issue by caojiajun** [netease-im/camellia#133]
Module: camellia-redis-proxy
Version: v1.2.14
Content: camellia-redis-proxy frontend tls bidirectional authentication not effective 

#130

**Comment by InputOutputZ** [comment]
I tested it, and confirm the fix is working perfectly. Thanks so much for all your work.

<img width="1105" alt="Screenshot 2023-08-22 at 10 29 00" src="https://github.com/netease-im/camellia/assets/4721398/c90cbe8d-bd0c-49d3-9faf-476462d118a2">

**Comment by caojiajun** [comment]
thank you very much for your testing~
