### ISSUE TITLE
连接池配制 

### ISSUE THREAD

**Issue by isoleo** [netease-im/camellia#14]
这个proxy 配制文件是否配制与后端redis 的连接 池。
类似jedis 的 max_active 或者 max_total 这个最大连接数的配制 ？
2、这个到proxy --> redis 连接 ，我看只有3个网络连接。这个是写死的吗? 
谢谢

**Comment by caojiajun** [comment]
proxy是异步模式，默认会启动cpu核数的工作线程，每个线程会建一个连接，正常情况下不需要特殊配置，如果要配置工作线程数（不要超过cpu核数），可以参考https://github.com/netease-im/camellia/blob/master/docs/redis-proxy/deploy.md ，拉到文档最底下

**Comment by isoleo** [comment]
其实我的需求是后端是兼容redis 协议 的其它存储，要靠多线程来提高性能，但是你们这个代理挺好用，就是没找到配制的参数名。
十分感谢。优秀

**Comment by caojiajun** [comment]
后端已经支持redis协议，为何不直连后端，是需要使用分片让后端多个节点组成集群么

**Comment by isoleo** [comment]
不是，是想用这个代理的双写功能 。写到两个数据中心。

**Comment by isoleo** [comment]
boss-thread: 1
    work-thread: 4
boss-thread 是什么意思呢？

**Comment by caojiajun** [comment]
固定填1即可，是用于处理新建连接的，可以加我微信：hdnxttl

**Comment by caojiajun** [comment]
完整配置可以看：CamelliaRedisProxyProperties.java
