### ISSUE TITLE
camellia-delay-queue 能否增加一个主动触发消息过期通知的api

### ISSUE THREAD

**Issue by fuhaodev** [netease-im/camellia#145]
Module: camellia-delay-queue
Content: 想使用 camellia-delay-queue 在实现一个长轮询的功能
接口A使用sendMsg发送延迟消息，hold住连接，如果消息到期接口返回，客户端继续轮询调用接口A；
接口B可以主动触发同一条消息过期回调，实现接口A立即响应结果。
看到api有deleteMsg的接口，但貌似没有触发回调，能否增加一个主动触发的接口。

**Comment by caojiajun** [comment]
"接口A使用sendMsg发送延迟消息，hold住连接，如果消息到期接口返回，客户端继续轮询调用接口A"
---- 这样做是为了什么

**Comment by fuhaodev** [comment]
> "接口A使用sendMsg发送延迟消息，hold住连接，如果消息到期接口返回，客户端继续轮询调用接口A" ---- 这样做是为了什么

有一个App扫码绑定设备的功能，设备端生成二维码然后轮询调用接口A查询绑定状态，App调用接口B扫码绑定，触发接口A响应，设备端拿到绑定结果

**Comment by fuhaodev** [comment]
> > "接口A使用sendMsg发送延迟消息，hold住连接，如果消息到期接口返回，客户端继续轮询调用接口A" ---- 这样做是为了什么
> 
> 有一个App扫码绑定设备的功能，设备端生成二维码然后轮询调用接口A查询绑定状态，App调用接口B扫码绑定，触发接口A响应，设备端拿到绑定结果

为了能减轻服务器压力和设备端能及时拿到绑定结果，采用的是长轮询，现有方案用redis的BLPOP和lpush实现的

**Comment by caojiajun** [comment]
用延迟队列替换blpop/lpush，优势是啥，有时候感觉还不如blpop/lpush来的直接

**Comment by caojiajun** [comment]
> > > "接口A使用sendMsg发送延迟消息，hold住连接，如果消息到期接口返回，客户端继续轮询调用接口A" ---- 这样做是为了什么
> > 
> > 
> > 有一个App扫码绑定设备的功能，设备端生成二维码然后轮询调用接口A查询绑定状态，App调用接口B扫码绑定，触发接口A响应，设备端拿到绑定结果
> 
> 为了能减轻服务器压力和设备端能及时拿到绑定结果，现有方案用redis的BLPOP和lpush实现的长轮询，这边环境变更redis不支持阻塞命令

哦哦，为啥redis不支持阻塞命令了

**Comment by caojiajun** [comment]
延迟队列目前也需要pubsub来做，你这个新环境的redis支持pubsub吗，pubsub也可以认为是一种广义的阻塞命令

**Comment by fuhaodev** [comment]
> 用延迟队列替换blpop/lpush，优势是啥，有时候感觉还不如blpop/lpush来的直接

是的，之前方案还是挺稳定的，这边环境迁移到了新的三方平台，他们的redis proxy不不支持

**Comment by fuhaodev** [comment]
> 延迟队列目前也需要pubsub来做，你这个新环境的redis支持pubsub吗，pubsub也可以认为是一种广义的阻塞命令

pubsub是支持的

**Comment by caojiajun** [comment]
让他们把proxy换成camellia-redis-proxy，这样就支持阻塞命令了，/捂脸

**Comment by fuhaodev** [comment]
> 让他们把proxy换成camellia-redis-proxy，这样就支持阻塞命令了，/捂脸

让他们换太难了，基本没太可能 /捂脸

**Comment by fuhaodev** [comment]
> 让他们把proxy换成camellia-redis-proxy，这样就支持阻塞命令了，/捂脸

我看到公司登记里他们的测试环境好像也用了camellia-redis-proxy？ /捂脸

**Comment by caojiajun** [comment]
那感觉你这边不如直接就用pubsub命令？设备直接去sub，sub到了就取消sub，然后返回，相当于一个blpop的效果
