### ISSUE TITLE
camellia-redis-proxy support for RedisInsight

### ISSUE THREAD

**Issue by arielzach** [netease-im/camellia#148]
Module: [camellia-redis-proxy]

Hello,

I'm trying to use [RedisInsight](https://github.com/RedisInsight/RedisInsight) with camellia-redis-proxy. I'm able to connect, but there are several commands that the proxy does not support, such as:

not support command = dbsize, count = 1
not support command = dbsize, count = 8
not support command = ft._list, count = 1
not support command = ft._list, count = 8
not support command = memory, count = 1
not support command = memory, count = 4
not support command = memory, count = 8
not support command = module, count = 1
not support command = monitor, count = 1
not support command = monitor, count = 2
not support command = slowlog, count = 1
not support command = tfunction, count = 1
not support command = tfunction, count = 8

Is it possible to add support for these commands?

**Comment by caojiajun** [comment]
this commands related to the server side info, such as dbsize\memory\slowlog\monitor\memory
as the backend of proxy maybe multiple redis servers, such commands will be ambiguity

further more, these not supported commands does not affect the use of RedisInsight ?

**Comment by caojiajun** [comment]
btw：

`dbsize` and `slowlog` maybe merge/sum the backend redis servers' reply
`ft._list` and `tfunction` maybe broadcast command to all the backend redis servers or/and merge the reply

`memory` and `monitor`  and `module`, these commands maybe inappropriate
