### ISSUE TITLE
想问一下redis-proxy组件如何自定义路由转发？

### ISSUE THREAD

**Issue by Cloud-Yao** [netease-im/camellia#151]
Module: camellia-redis-proxy
Version: v1.2.16
Content: 
我在配置文件中配置了两个Redis地址，能不能自定义在转发后端redis时进行拦截，然后可以自己自定义决定转发到这两个redis中的哪一个。实际场景是我想结合内置的hot-key插件，通过判断某个key是否是热key，然后决定转发到两个redis中的其中一个redis。

**Comment by caojiajun** [comment]
这个需要增强一下当前的plugin功能，可以1.2.17里去支持一下，加微信群里讨论一下实现方案吧

**Comment by caojiajun** [comment]
1.2.17 已经release，相关功能已经支持 @Cloud-Yao

**Comment by Cloud-Yao** [comment]
- 好的，非常感谢

**Comment by caojiajun** [comment]
> * 好的，非常感谢

欢迎加微信群，后续沟通方便一点：
![image](https://github.com/netease-im/camellia/assets/10111708/019502ac-f27c-4b1b-b1e1-730cc40fe2be)
