### ISSUE TITLE
Camellia-redis-proxy 固定 redis 版本号问题

### ISSUE THREAD

**Issue by Provinm** [netease-im/camellia#153]
https://github.com/netease-im/camellia/blob/82d0c9df061346b73db209f28b642ad82e309495/camellia-redis-proxy/camellia-redis-proxy-core/src/main/java/com/netease/nim/camellia/redis/proxy/info/ProxyInfoUtils.java#L247

固定版本号会造成 client 端获取基础信息时产生误解

**Comment by Provinm** [comment]
建议如果不能在此提供真实的 redis 版本号的话，给一个 `not provided` 也可以

**Comment by caojiajun** [comment]
spring actuator默认会使用info命令返回的redis_version字段来做健康检查
字段不能为空，否则spring actuator会认为proxy异常

6.2.6可以认为是proxy当前支持的命令已经覆盖了redis6.x
