### ISSUE TITLE
Redis Proxy是否支持将Tair相关命令运行在Redis server上？

### ISSUE THREAD

**Issue by clytzelbj** [netease-im/camellia#154]
Module: [camellia-redis-proxy]
Version: [latest]
Content: [redis-proxy的文档中提到，可以支持阿里云Tair相关的命令，但server端对接支持仅提到了几种redis的不同部署模式。请问该Proxy可以支持在社区版的Redis实例上运行Tair相关的命令吗？还是要求server端本身支持相关命令才行？Proxy仅提供读写分离、负载均衡等方面的功能？]

**Comment by caojiajun** [comment]
1、需要server端支持tair命令才行（社区版运行tair开源的module就行了吧）
2、proxy支持识别tair相关的命令并进行正确的路由（如分片、读写分离、双写等）
