### ISSUE TITLE
云信redis代理和官方推出的Redis cluster proxy之间的区别？

### ISSUE THREAD

**Issue by beifeng15** [netease-im/camellia#2]
您好，现在正在研究云信的redis代理,想咨询一下您以下问题？
1.官方已经推出了Redis 6.0多线程版本，那么云信redis使用netty实现代理的方式，是不是不占优势。
2.官方其实也推出了相关的Redis cluster proxy,那么相比官方的redis cluster proxy云信proxy有什么特别之处？
上面是我的一些问题，只是单纯的想明白云信的优势，然后选择使用。非常感谢您能够解答一下

**Comment by caojiajun** [comment]
1、camellia-redis-proxy和redis6.0的多线程特性本身没有关系吧，一个是proxy，一个redis本身
2、相比官方redis-cluster-proxy，camellia-redis-proxy提供了以下一些功能：
1）结合camellia-dashboard，可以不重启动态切换代理的后端
2）支持在proxy层进行双写：某些业务场景下可以在redis本身高可用基础上再做一层高可用；在其他一些场景下可以做数据迁移（区别于redis集群层面的全量迁移）
3）支持在proxy层进行分片：比如可以把多个redis集群（单个redis cluster集群存在节点数的上限）作为逻辑上的单个集群进行使用
4）camellia-redis-proxy提供了一个spring-boot-starter，可以比较方便的接入eureka、consul等注册中心服务，从而可以进行客户端负载均衡，这样proxy层之前可以省掉一层用于保证proxy本身高可用和水平扩展的lb层（如lvs），减少了网络上的一跳

**Comment by mac119** [comment]
camellia-redis-proxy  只支持Java 应用吧。

**Comment by caojiajun** [comment]
> camellia-redis-proxy 只支持Java 应用吧。

camellia-redis-proxy实现了redis协议，任意客户端均可以像连接redis一样去连接camellia-redis-proxy

**Comment by caojiajun** [comment]
几款开源redis-proxy的对比可以参考这里：
https://github.com/netease-im/camellia/blob/master/docs/redis-proxy/performance-report-8.md

**Comment by mac119** [comment]
> > camellia-redis-proxy 只支持Java 应用吧。
> 
> camellia-redis-proxy实现了redis协议，任意客户端均可以像连接redis一样去连接camellia-redis-proxy

感谢回复哈， 但是我没有看到比较详细的配置文档。关于不同开发语言的。

**Comment by caojiajun** [comment]
> > > camellia-redis-proxy 只支持Java 应用吧。
> > 
> > 
> > camellia-redis-proxy实现了redis协议，任意客户端均可以像连接redis一样去连接camellia-redis-proxy
> 
> 感谢回复哈， 但是我没有看到比较详细的配置文档。关于不同开发语言的。

你要怎么样的文档，对于客户端来说，用各个语言标准的redis客户端sdk去连接proxy即可

**Comment by mac119** [comment]
> > > > camellia-redis-proxy 只支持Java 应用吧。
> > > 
> > > 
> > > camellia-redis-proxy实现了redis协议，任意客户端均可以像连接redis一样去连接camellia-redis-proxy
> > 
> > 
> > 感谢回复哈， 但是我没有看到比较详细的配置文档。关于不同开发语言的。
> 
> 你要怎么样的文档，对于客户端来说，用各个语言标准的redis客户端sdk去连接proxy即可

整体部署的文档，组件部署的文档等。另外我们有相关的讨论组或者群吗。 我们想使用，但是又怕有问题找不到人。。。。

**Comment by caojiajun** [comment]
> > > > > camellia-redis-proxy 只支持Java 应用吧。
> > > > 
> > > > 
> > > > camellia-redis-proxy实现了redis协议，任意客户端均可以像连接redis一样去连接camellia-redis-proxy
> > > 
> > > 
> > > 感谢回复哈， 但是我没有看到比较详细的配置文档。关于不同开发语言的。
> > 
> > 
> > 你要怎么样的文档，对于客户端来说，用各个语言标准的redis客户端sdk去连接proxy即可
> 
> 整体部署的文档，组件部署的文档等。另外我们有相关的讨论组或者群吗。 我们想使用，但是又怕有问题找不到人。。。。

直接加我微信吧：hdnxttl
