### ISSUE TITLE
关于密码部分的疑惑

### ISSUE THREAD

**Issue by emperorjoker** [netease-im/camellia#21]
你好，

我看到camellia redis proxy支持设定密码，我想了解对应redis cluster proxy里的auth口令部分，在camellia redis proxy中应该如何设置？

**Comment by caojiajun** [comment]
最简单的：可以在application.yml里配置即可，此时全局一个密码

扩展：基于自定义的ClientAuthProvider和ProxyRouteConfUpdater可以实现用passwordA登录proxy路由到redisA，用passwordB登录proxy路由到redisB

如有更多疑惑可以添加微信
