### ISSUE TITLE
command: (GEORADIUS_RO) not support

### ISSUE THREAD

**Issue by aa1215018028** [netease-im/camellia#216]
Module: [camellia-redis-proxy]
Content:  command: (GEORADIUS_RO) not support , cluster pattern

**Comment by wozaizhe55** [comment]
I can support it.

**Comment by caojiajun** [comment]
supported:

[GEOADD](https://redis.io/commands/geoadd/)
[GEODIST](https://redis.io/commands/geodist/)
[GEOHASH](https://redis.io/commands/geohash/)
[GEOPOS](https://redis.io/commands/geopos/)
[GEORADIUS](https://redis.io/commands/georadius/)
[GEORADIUSBYMEMBER](https://redis.io/commands/georadiusbymember/)
[GEOSEARCH](https://redis.io/commands/geosearch/)


not supported:

- [ ] [GEORADIUSBYMEMBER_RO](https://redis.io/commands/georadiusbymember_ro/)
- [ ] [GEORADIUS_RO](https://redis.io/commands/georadius_ro/)
- [ ] [GEOSEARCHSTORE](https://redis.io/commands/geosearchstore/)

**Comment by caojiajun** [comment]
#223
