### ISSUE TITLE
请问pipeline模式会丢失命令吗？

### ISSUE THREAD

**Issue by UsamiRenko97** [netease-im/camellia#22]
目前看是用AsyncTaskQueue类支持了pipeline模式。如果一个pipeline中有10个命令，queue中有10个AsyncTask，调用10次callback方法。

如果连续调用10次callback方法，只有第一次生效，其余九次直接返回，如果第一次writeAndFlush时有网络异常导致走到finally里了，但channelInactive又没有触发，是不是会导致pipeline的10条命令一直留在queue中，直到客户端再次请求？而且客户端再次请求时，回复的是上次pipeline中的命令导致异常。如果客户端一段时间内没有再次请求，上一次的pipeline命令会超时失败。

目前没有试过这种情形，想请问下上面这种说法成不成立？

**Comment by caojiajun** [comment]
网络异常不会导致writeAndFlush方法抛异常吧

客户端超时的话端侧应该关掉连接，可以理解连接已经Broken了，可以参考http协议

有问题可以加微信~
