### ISSUE TITLE
command return NOT_AVAILABLE

### ISSUE THREAD

**Issue by isoleo** [netease-im/camellia#23]
我后端对接的是pika 。报这个错误 有点不理解 。看连接 ，还连上来了，最后总是报这么个错误 。。。
ERROR error-log-collector-pool-7-thread-1  c.n.n.c.r.p.u.ErrorLogCollector:62 - com.netease.nim.camellia.redis.proxy.command.async.RedisClient:RedisClient[@10.10.251.11:6379][id=53] stopping, command return NOT_AVAILABLE, count = 1

**Comment by caojiajun** [comment]
看上去是连接被后端关掉了，有没有完整的日志？或者加微信沟通
