### ISSUE TITLE
ReplyEncoder:channel not active

### ISSUE THREAD

**Issue by isoleo** [netease-im/camellia#24]
时不时的就会报这个错误 
ERROR error-log-collector-pool-7-thread-1  c.n.n.c.r.p.u.ErrorLogCollector:62 - com.netease.nim.camellia.redis.proxy.netty.ReplyEncoder:channel not active, remote.ip=/10.120.5.63:47359, count = 1

我记得重启，刚起动完，就会报一下。然后偶尔就会报一个

**Comment by caojiajun** [comment]
1、这个表示客户端关闭了连接（大概率是客户端超时导致主动关闭了连接），目前超时时间多久？
2、cpu是几核的，work-thread有没有显式设置？（一搬建议不要显式设置，自动获取就行），如果设置不合理会降低proxy性能，引起超时问题

**Comment by isoleo** [comment]
work-thread 10 2核处理器。后端是pika

**Comment by caojiajun** [comment]
work thread不能高于cpu核数，你设置成2再观察吧

**Comment by isoleo** [comment]
好的，谢了
