### ISSUE TITLE
fail[syntax error] in camellia-redis-proxy log once in a while

### ISSUE THREAD

**Issue by cxyfreedom** [netease-im/camellia#248]
Module: camellia-redis-proxy
Version: v1.2.23
Content: web service connect camellia-redis-proxy with redis cluster, If I get some data from camellia-redis-proxy, the proxy log record `fail[syntax error] count=x` once in a while

**Comment by caojiajun** [comment]
Could you provide more error log?

`syntax error` usually means command args incorrect

**Comment by caojiajun** [comment]
![image](https://github.com/netease-im/camellia/assets/10111708/245d84ef-a6df-4ecd-93a8-e8533fd74134)

you can join wechat group
