### ISSUE TITLE
 camellia-redis-proxy syntax error

### ISSUE THREAD

**Issue by hudachui1224** [netease-im/camellia#254]
Module: [e.g. camellia-redis-proxy syntax error]
Version: [e.g. v1.2.27]
Content: [camellia-redis-proxy log  fail[syntax error] count=x]
怎么样才能知道具体 是那些命令会有这样的错误？
不清楚具体错误的命令，需要确认到底是因为camellia-redis-proxy本身不支持这种命令，还是因为command 的语法错误。

**Comment by caojiajun** [comment]
试试grep 'syntax error' 一下，看看有没有其他信息

**Comment by hudachui1224** [comment]
grep 'syntax error' 并没有相关的信息。
这种日志 看样子都是  由监控端口 获取 client_fail 统计的信息 并不包含具体command的,而 proxy 本身的 log 也没有相关的信息。
![image](https://github.com/netease-im/camellia/assets/171679181/de5adae8-43d7-4c42-b0bd-1f251b5b90ab)

**Comment by caojiajun** [comment]
是否可以提供一下完整的日志文件，我这边可以看看能不能定位到哪个命令触发的

**Comment by hudachui1224** [comment]
[redis-proxy-dcfc96d49-9ccjs_redis-proxy.log](https://github.com/user-attachments/files/15584740/redis-proxy-dcfc96d49-9ccjs_redis-proxy.log)
这是运行在 k8s 里 pod的log，所有能看到只是这些日志。要是能把导致 syntax error的 整条命令 记录到日志 就好了。

**Comment by caojiajun** [comment]
![image](https://github.com/netease-im/camellia/assets/10111708/d7f1f72e-24c0-4ee4-aea1-543bb25f23fc)

99%是client命令，当前client命令只支持`getname\setname\info\list`这四个参数，其他参数会返回`syntax error`

**Comment by caojiajun** [comment]
欢迎加入微信技术群哦 :)
