### ISSUE TITLE
请问是否会输出双写或多写的延时？

### ISSUE THREAD

**Issue by fengnex** [netease-im/camellia#26]
如题

**Comment by caojiajun** [comment]
不知道你说的双写指的是proxy的直接双写还是基于kafka的双写

对于前者，双写是并发执行的，基本可以认为是同时的，你甚至可以配置成2个redis同时写成功再返回客户端成功
对于后者，你可以通过kafka的消费延迟情况来判断双写延迟情况

有更多问题可以加微信沟通

**Comment by caojiajun** [comment]
对于直接双写模式（区别于基于kafka的双写模式），1.0.44开始，支持监控到后端的读写延时
