### ISSUE TITLE
如果代理Redis Cluster，Key路由逻辑是什么？

### ISSUE THREAD

**Issue by chanjarster** [netease-im/camellia#27]
如果代理Redis Cluster，Key路由逻辑是什么？

* 和官方一样CRC16，直接把Key路由到正确Slot上
* 和普通客户端一样，随便路由到某个节点，通过 MOVED/ASK 来重定向到正确Slot上

另外，如果代理Redis Cluster，自定义sharding还能用吗？

**Comment by caojiajun** [comment]
会计算CRC16，然后定位到正确的节点；同时如果后端redis-cluster有节点扩缩容导致slot变更，proxy会刷新路由表，也会通过MOVED/ASK来重定向

如果你需要camellia同时代理到多组redis-cluster集群，此时你可以用自定义sharding，来组成一个超大规模的集群
换一种说法，自定义sharding中，一个redis-cluster集群是被当做一个node的

**Comment by segment11** [comment]
@caojiajun 如果是custom sharding，这个功能有有么？
同时如果后端redis-server有节点扩缩容导致自定义的slot变更，会返回move命令，proxy会刷新路由表不？

**Comment by caojiajun** [comment]
custom sharding都是静态路由，就没有刷新路由的说法了

**Comment by zhangyukai** [comment]
> > > 会计算CRC16，然后定位到正确的节点；同时如果后端redis-cluster有节点扩缩容导致slot变更，proxy会刷新路由表，也会通过MOVED/ASK来重定向
> > > 如果你需要camellia同时代理到多组redis-cluster集群，此时你可以用自定义sharding，来组成一个超大规模的集群 换一种说法，自定义sharding中，一个redis-cluster集群是被当做一个node的
> > 
> > 
> > ---redis cluster原生的是计算key的hash值，路由到哪个slot。 camellia如何得知这个slot具体在哪个节点呢?
> 
> 这里有2个概念，一个是camellia的分片，一个是redis-cluster的分片
> 
> camellia会先根据分片函数（可自定义）计算出自己的bucket（或者叫slot），从而找到目标集群（可能是一个redis-standalone，也可能是一个redis-cluster），随后再路由到对应的redis-cluster的节点，此时就是根据redis-cluster官方的slot计算方法去计算了

了解了，多谢！
