### ISSUE TITLE
redis-proxy的伪redis-cluster模式时，类似原生redis中的cluster-announce-port和cluster-announce-bus-port的配置项

### ISSUE THREAD

**Issue by OceanFot** [netease-im/camellia#330]
在使用redis-proxy的伪redis-cluster模式时，希望可以增加类似原生redis中的 `cluster-announce-port` 和 `cluster-announce-bus-port`
配置项（用于在K8s外部进行访问K8s内部署的redis-proxy）

目前是在K8s中部署的redis-proxy，使用`cluster nodes`获取到的节点信息中，ip、端口、bus端口均是K8s内网的，如果应用程序和部署的redis-proxy不在同一个k8s集群中，是无法访问到的。
目前通过设置proxy.node.current.host已经成功将ip调整了，但是暂时没有调整端口的地方

谢谢~

**Comment by OceanFot** [comment]
可能存在的一个问题：如果启动多副本的情况下，这个配置项就不太适应了（所有副本中都使用了同一个地址+端口）

**Comment by caojiajun** [comment]
需要你每个pod都不一样的配置

**Comment by OceanFot** [comment]
感谢
