### ISSUE TITLE
camellia-redis-client 不支持 redis-cluster-slaves

### ISSUE THREAD

**Issue by ztkaoqin** [netease-im/camellia#335]
Module: camellia-redis-client
Version: 1.2.27
Content: 我们在用camellia-redis-client 作为JedisClient 访问 redis-cluster集群时，期望能够实现读写分离。

但是我使用 redis-cluster-slaves://时， 发现并不支持。。。

请问下， 我该怎么做？

**Comment by caojiajun** [comment]
支持的，可以发一下完整配置

**Comment by caojiajun** [comment]
我知道你的意思了，当前camellia-redis-proxy支持，但是camellia-redis-client（CamelliaRedisTemplate）还不支持

**Comment by ztkaoqin** [comment]
> 我知道你的意思了，当前camellia-redis-proxy支持，但是camellia-redis-client（CamelliaRedisTemplate）还不支持
是的, 所以希望能够快点支持.
{
  "type": "simple",
  "operation": {
    "read": "redis-cluster://password@127.0.0.1:3306",
    "type": "rw_separate",
    "write": "redis-cluster-slaves://pwd@127.0.0.1:51002?withMaster=false"
  }
}

**Comment by caojiajun** [comment]
可以一起共建呀，来么，可以加我微信：hdnxttl

**Comment by caojiajun** [comment]
#351 351
