### ISSUE TITLE
双写网络故障问题

### ISSUE THREAD

**Issue by ONG-YA** [netease-im/camellia#35]
你好，请问下，双写过程如果某个机房网络故障，双写出现问题这种情况怎么补救，有没有办法让数据做到最终一致性，或者该程序是否已经考虑并解决这个问题了？

**Comment by caojiajun** [comment]
1、可以基于kafka做双写（当前已支持），当双写集群故障时使用kafka实现一定的堆积能力
2、基于redis-shake等工具来做全量同步来补偿
3、忽略这种情况，比如ttl就1天，那就有1天的不一致，再过1天就一致了

备注：使用双写模式做跨机房灾备方案，不能保证100%的数据一致性，需要结合业务特点来使用

如果有需要可以加微信进一步沟通

**Comment by avyou** [comment]
请问如果使用 redis-shake 或 redis-port 工具全量同步，因为两边是 codis 分片的，是否没办法进行？
如果用工具指定源 camellia-redis-proxy 的外网IP，好像是不支持？ 经过 camellia 同步时会报错。
谢谢！

**Comment by caojiajun** [comment]
这边camellia-redis-proxy后端挂的是多组redis-standalone么

**Comment by caojiajun** [comment]
> 请问如果使用 redis-shake 或 redis-port 工具全量同步，因为两边是 codis 分片的，是否没办法进行？ 如果用工具指定源 camellia-redis-proxy 的外网IP，好像是不支持？ 经过 camellia 同步时会报错。 谢谢！

1、camellia-redis-proxy支持使用redis-shake的sync和rump两种模式进行数据的迁入，sync模式支持存量数据和增量数据的迁移，rump模式仅支持存量数据迁移
2、如果要把camellia-redis-proxy作为源，目前仅支持scan方式进行扫描的方式进行同步，不支持生成dump文件，也不能作为master节点挂slave；或者你也可以直接以camellia-redis-proxy后端的多个redis节点作为多个源进行同步

如果有需要也可以加微信沟通：hdnxttl
