### ISSUE TITLE
有没有完善管理后台的计划

### ISSUE THREAD

**Issue by lihuayong** [netease-im/camellia#4]
dashboard提供的功能过于简单，操作数据，很容易出错？有没有提供监控功能的计划呢？以后对于这个项目还有哪些功能的升级？

**Comment by caojiajun** [comment]
1、dashboard当前只是一个swagger-ui的页面，暂时没有开发专门的前端ui的计划。
2、监控当前已经有了，一个是redis proxy本身可以开启监控（连接数、请求数、耗时等，监控间隔秒数自定义），还一个是可以上报给dashboard（每分钟上报一次各命令请求数）。上述的监控数据的可视化可以对接到你们自己的可视化平台上
3、等1.0.9 release后，暂时没有新的功能开发计划，你可以看看你还需要哪些，我们这边会看情况评估

**Comment by lihuayong** [comment]
1.0.9版本计划什么时候发布？

**Comment by caojiajun** [comment]
功能基本OK了，等性能QA完成新老版本性能测试回归就会发release包到maven中央仓库，预计1-2周内。
你可以拉最新代码（master分支）到本地编译进行测试

有问题可以加我微信：hdnxttl
