### ISSUE TITLE
renew namespace = xxx, workerId = xxx fail

### ISSUE THREAD

**Issue by junneyang** [netease-im/camellia#40]
启动运行一会之后，打这个日志，这个问题产生的原因是什么

**Comment by caojiajun** [comment]
能不能提供一下完整日志

**Comment by junneyang** [comment]
> 能不能提供一下完整日志

日志只有这个
![image](https://user-images.githubusercontent.com/6802322/176115226-c350841b-ec24-4ff0-b65b-143a9159fff4.png)

**Comment by caojiajun** [comment]
我这边没有复现，要不加个微信沟通一下：hdnxttl
