### ISSUE TITLE
redis proxy参数最佳实践

### ISSUE THREAD

**Issue by tain198127** [netease-im/camellia#45]
1. ### 背景

redis proxy 作为一个大型redis cluster集群的proxy。
该cluster 为110个master 110个slave。
proxy节点数为10个节点。在客户端使用lettuce作为连接，并根据请求进行了负载均衡。
压测VUSER 1200

2. ### 现象

压测到一定流量后，出现no child group等错误。该问题应该是netty的child group无法再处理了。

3. ### 问题分析
发现在源码中 soBacklog的值设置为1024.该值在大集群海量并发情况下，是否合理？不确定该问题是否由这个设置导致的。

4. ### 期望
是否可以提供一些针对不同场景的参数最佳实践？

**Comment by caojiajun** [comment]
1、能否提供一下错误日志
2、压测客户端lettuce是否只管发，不管收，纯异步的发送命令呢
3、压测proxy是部署于云主机、物理机还是容器？proxy的配置是怎么样的（默认配置？）
4、目前包括网易内部和外部客户，一般都是用的默认配置既能满足各种业务场景，需要了解一下你们压测场景有哪些特征
