### ISSUE TITLE
Cannot test performance by redis-benchmark

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#47]
Hi @caojiajun, I want to say camellia is an excellent project. Thank you all. <3

Follow by [performance-report.md](https://github.com/netease-im/camellia/blob/ffb2697e45898af4a2d3b5d8bbfbb4763764a64f/docs/redis-proxy/performance/performance-report.md), I try to  `test performance` by `redis-benchmark`, but I got an issue:
```
 ~ redis-benchmark -n 1000000 -r 10000 -c 200 -t set,get,incr,lpush,rpush,lpop,rpop,sadd,hset,spop,lpush,lrange -q -p 6380 -h [myhost] -a [pass]
ERROR: Not Support
ERROR: failed to fetch CONFIG from [myhost]:6380
WARNING: Could not fetch server CONFIG
SET: rps=0.0 (overall: 0.0) avg_msec=nan (overall: nan) 
```

and I read the code of this project do not support the `CONFIG` redis command:
`    
CONFIG(CommandSupportType.NOT_SUPPORT, null, null, Blocking.FALSE, null),
`

How can you benchmark `camellia-redis-proxy` with `redis-benchmark`.

Again, Thank you so much!

**Comment by caojiajun** [comment]
try start proxy/redis-benchmark without password first.

I will find out the reason why proxy with password do not work on redis-benchmark later.

CONFIG command may support in 1.1.3 version.

**Comment by tasszz2k** [comment]
Let me trace with you

**Comment by tasszz2k** [comment]
> CONFIG command may support in 1.1.3 version.

You might consider adding the option to disable some features(`redis command`) by configuring the `camellia-redis-proxy.properties` file. Because not every feature should be enabled in some environments.
For example, I only want to enable `CONFIG` command on `dev` environment for benchmarking, but I don't want to enable it on `prod` environment because of some security issues.

**Comment by caojiajun** [comment]
> > CONFIG command may support in 1.1.3 version.
> 
> Might you consider adding the option to disable some features(`redis command`) by configuring the `camellia-redis-proxy.properties` file? Because not every feature should be enabled in some environments. For example, I only want to enable `CONFIG` command on `dev` environment for benchmarking, but I don't want to enable it on `prod` environment because of some security issues.
> 
> ```
> redis-command.disable=CONFIG,INFO,HELLO,FLUSHDB,...
> ```

That is a good suggestion.

**Comment by caojiajun** [comment]
> Let me trace with you

it's a bug, 1.1.3 will fix.

https://github.com/netease-im/camellia/commit/ecbcad133d9a51a04d38d8220f9342a0e4a5e96c

**Comment by caojiajun** [comment]
> > CONFIG command may support in 1.1.3 version.
> 
> Might you consider adding the option to disable some features(`redis command`) by configuring the `camellia-redis-proxy.properties` file? Because not every feature should be enabled in some environments. For example, I only want to enable `CONFIG` command on `dev` environment for benchmarking, but I don't want to enable it on `prod` environment because of some security issues.
> 
> ```
> redis-command.disable=CONFIG,INFO,HELLO,FLUSHDB,...
> ```

here:
https://github.com/netease-im/camellia/commit/c2298c5eeec0743fc976b700fceafa6e3264ec31

**Comment by tasszz2k** [comment]
> here: [c2298c5](https://github.com/netease-im/camellia/commit/c2298c5eeec0743fc976b700fceafa6e3264ec31)

That's a great feature.
I'm surprised you developed it so fast.
:"]]

**Comment by caojiajun** [comment]
1.1.3 will support 'CONFIG GET xxx' command

https://github.com/netease-im/camellia/commit/c1b09657450520eb5d27f5124350b7506bb31a90
