### ISSUE TITLE
[Camellia-redis-proxy] Maven dependency pulling a wrong dependency 

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#49]
I try to upgrade `camellia` to version `v1.1.3`, so I found an error  `Maven dependency pulling a wrong dependency` (maybe since `v.1.1.2`, I test with `v1.1.1` still works)

```xml
....
		<dependency>
			<groupId>com.netease.nim</groupId>
			<artifactId>camellia-redis-proxy-spring-boot-starter</artifactId>
			<version>1.1.3</version>
		</dependency>

....
```

- V1.1.1:
![image](https://user-images.githubusercontent.com/48039235/197997165-252a7fbb-3702-4a0b-a7db-243757f1ee0e.png)

- V1.1.3: 
![image](https://user-images.githubusercontent.com/48039235/197997393-170250e7-8276-4360-983a-6e091871fd17.png)

==> The consequence is cannot load classes of `camellia-redis-proxy` module
![image](https://user-images.githubusercontent.com/48039235/197997948-e9c078db-0df3-4e5b-9629-b0fa41a6879b.png)

**Comment by tasszz2k** [comment]
@caojiajun  can you check it?
:"||

**Comment by caojiajun** [comment]
check from here:
https://repo1.maven.org/maven2/com/netease/nim/camellia-redis-proxy/1.1.3/

**Comment by tasszz2k** [comment]
I tried again it seems to be a bug
Let's create a new project and use dependencies of file POM [/camellia-redis-proxy-samples/pom.xml](https://github.com/netease-im/camellia/blob/v1.1.3/camellia-samples/camellia-redis-proxy-samples/pom.xml)

**Comment by tasszz2k** [comment]
> seems correct in maven central
Yes, I downloaded this `.jar` file and it works, but it doesn't work using the maven dependency
:"<<

**Comment by caojiajun** [comment]
try clean you local maven repository

**Comment by tasszz2k** [comment]
> try clean you local maven repository

Ok, let me try

**Comment by tasszz2k** [comment]
> > try clean you local maven repository
> 
> Ok, let me try

It works
My Fault 
:"<<

**Comment by tasszz2k** [comment]
thank you so much
