### ISSUE TITLE
双写是否能保证原子性

### ISSUE THREAD

**Issue by lihuayong** [netease-im/camellia#5]
我们公司的项目都是发布在两个机房里面，采用的是异地双机房部署，双写功能，能不能做到原子性呢？

**Comment by caojiajun** [comment]
做不到，只能保证来自A连接的命令1、命令2、命令3等在两个后端redis中的执行顺序是一样的

**Comment by lihuayong** [comment]
有打算要支持吗？很多公司都是采用的异地双机房部署，如果要做到多个机房数据备份，有什么好的方法呢？
如果不保证原子性的话，双写的使用场景有哪些呢？感觉这个功能就很弱了

**Comment by caojiajun** [comment]
redis本身不支持完整的事务，所以不是我们不支持，是做不到呀~
云信内部主要用途是用于缓存类数据的迁移工作，比如业务A和业务B共享redis1，然后业务增长了，需要把A和B的redis分开部署，这个时候传统的方法是建一个redis2，容量至少和redis1一样，然后同步过来，然后业务A或者B切一个过来，然后断掉同步。
有了双写之后，就不需要建一个和redis1一样容量的redis2了，容量按需建，然后双写个几天，然后直接切过来。
