### ISSUE TITLE
Dynamic update ip check proxy from camelliadashboard

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#52]
hi @caojiajun, 
Now we're having `ipCheckerPlugin` - A plugin for IP black and white list restrictions on clients accessing the proxy. But It still read the configuration from file `camellia-redis-proxy.properties`.
 Should we provide a new Ip Checker Plugin: `dynamicIpCheckerPlugin`, It will read configurations via `camellia-dashboard` like how we fetch data from that. We will store these configurations in the database instead of a file.

```sql
create table camellia_ip_checker
(
    id          bigint(64) auto_increment comment 'Auto increment field'
        primary key,
    bid         bigint(64)    null comment 'bid',
    bgroup      varchar(64)   null comment 'bgroup',
    mode        tinyint(1)    not null comment '0=UNKNOWN, 1=BLACK, 2=WHITE',
    ip_list     varchar(1024) not null comment 'support ip, also supports network segment, comma separated.ex:2.2.2.2,5.5.5.5,3.3.3.0/24,6.6.0.0/16',
    create_time varchar(64)   null comment 'create time',
    update_time varchar(64)   null comment 'Update time',
    constraint bid_bgroup_unique
        unique (bid, bgroup)
)
    comment 'IP checker table' charset = utf8;


```

**Comment by caojiajun** [comment]
you can create a PR for this function

**Comment by tasszz2k** [comment]
I created a new pull request https://github.com/netease-im/camellia/pull/53 :  help me review it, thank you so much @caojiajun

**Comment by caojiajun** [comment]
add result-cache for ip-check-plugin

https://github.com/netease-im/camellia/commit/6dd2ed8d13b4118599e613be7169c654c9571a69
