### ISSUE TITLE
Fix Log4j Vulnerability

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#55]
`Camellia` is using dependencies:
```
Maven: org.apache.logging.log4j:log4j-api:2.10.0
Maven: org.apache.logging.log4j:log4j-to-slf4j:2.10.0
```
Please recheck and upgrade the version of log4j:
- https://logging.apache.org/log4j/2.x/security.html
- https://geekflare.com/scan-and-fix-log4j-vulnerability/

**Comment by caojiajun** [comment]
camellia only use slf4j and logback, which module use log4j2?

**Comment by tasszz2k** [comment]
![image](https://user-images.githubusercontent.com/48039235/202431673-cb6fdf8f-a635-457a-87ab-6852f421fefd.png)
![image](https://user-images.githubusercontent.com/48039235/202431845-1e7daa31-64f0-4dc9-96b3-28f0630fdcdb.png)

I'm not sure. I found them in the External Libraries of the `Camellia` project

**Comment by caojiajun** [comment]
i know,  spring-boot-starter-logging import it, but spring-boot enbled logback by default
