### ISSUE TITLE
配置读写分离的resource-table.json打成jar包通过docker部署时读取不到文件的问题

### ISSUE THREAD

**Issue by 904648702** [netease-im/camellia#6]
2021-01-29 03:47:45.763 ERROR 1 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commandInvoker' defined in class path resource [com/netease/nim/camellia/redis/proxy/springboot/CamelliaRedisProxyConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netease.nim.camellia.redis.proxy.command.CommandInvoker]: Factory method 'commandInvoker' threw exception; nested exception is java.lang.IllegalArgumentException: not found redis-proxy-0.0.1-SNAPSHOT/BOOT-INF/classes!/resource-table.json

**Comment by caojiajun** [comment]
显式的设置一下classpath试试

**Comment by hanxiaodong100** [comment]
> 显式的设置一下classpath试试

也不行，是读取方式的问题，jar中的文件还是需要使用流来读取getResourceAsStream

**Comment by caojiajun** [comment]
那你这边最后是改了camellia代码么，可以加个wx：hdnxttl
