### ISSUE TITLE
Bug: Camellia does not renew cluster info when Redis cluster is changed

### ISSUE THREAD

**Issue by phuc1998** [netease-im/camellia#65]
We should immediately renew slots when having any node down, but currently it is not

**Comment by caojiajun** [comment]
pls see this method: 
```
AsyncCamelliaRedisClusterClient#getClient
```

and see line549 of AsyncCamelliaRedisClusterClient.java

https://github.com/netease-im/camellia/blob/master/camellia-redis-proxy/src/main/java/com/netease/nim/camellia/redis/proxy/upstream/cluster/AsyncCamelliaRedisClusterClient.java

**Comment by phuc1998** [comment]
`AsyncCamelliaRedisClusterClient#getClient` renew when redis client == null or connection is idle right? how does camellia renew when nodes of cluster down

**Comment by phuc1998** [comment]
I means slave is promoted to master

**Comment by caojiajun** [comment]
case1: master down, slave promoted to master
master node will invalid and connect refused, so `getClient` method will get null for the old master node, proxy will try renew

case2: master alive, slave promoted to master inside the plan
the old master node will return `MOVED` reply, proxy will redirect to the new master node and try renew

**Comment by phuc1998** [comment]
many thanks
