### ISSUE TITLE
1.1.9版本长轮询拉消息时msg有中文乱码问题

### ISSUE THREAD

**Issue by ax3353** [netease-im/camellia#79]
我运行了大佬的delay-queue的sample时发现中文乱码问题。
发送的消息中文正常
![image](https://user-images.githubusercontent.com/32057578/209644754-a2382235-ef11-4ecc-81a6-add0d8cc37b6.png)
拉取的消息中文乱码
![image](https://user-images.githubusercontent.com/32057578/209644909-cb4b169a-f3df-437b-a0c3-6973124b77d9.png)
将方法com.netease.nim.camellia.delayqueue.server.springboot.CamelliaDelayQueueController#longPollingMsg中的httpServletResponse设置下编码为utf-8就没问题了，大佬有空修复下哈

**Comment by caojiajun** [comment]
方便的话，你可以提一个Pull requests哈～

**Comment by caojiajun** [comment]
https://github.com/netease-im/camellia/pull/81
