### ISSUE TITLE
[Camellia-redis-proxy] Monitoring wrong statistics of the redis_proxy_redis_connect_stats stats

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#88]
Module: [camellia-redis-proxy]
Version: [v1.1.11]
Content: [Monitoring wrong statistics of the redis_proxy_redis_connect_stats stats]
Issue ref: https://github.com/netease-im/camellia/issues/66

---

### 1. The "real" connection to the redis cluster resource
![image](https://user-images.githubusercontent.com/48039235/211966683-5bb39457-afdf-4d94-a0d8-aa1580181af8.png)

### 2. The redis_proxy_redis_connect_stats stats
![image](https://user-images.githubusercontent.com/48039235/211966809-311e880c-f63e-4661-8e25-75427d3f0baa.png)

### 3. Logs
![image](https://user-images.githubusercontent.com/48039235/211968475-efae2631-cb72-407f-934f-4829d90d6e9f.png)

### 4. Trace
- I deploy 6 instances, each redis proxy instance has ~1x redis connections
- But The `redis_proxy_redis_connect_stats stats` ~= 2x The `"real" connection to the redis cluster resource`

**Comment by caojiajun** [comment]
could you pls use `netstat apn | grep xxx` to confirm the real connection between proxy and redis

**Comment by tasszz2k** [comment]
> could you pls use `netstat apn | grep xxx` to confirm the real connection between proxy and redis

perhaps incorrect visualize on grafana
