### ISSUE TITLE
[Camellia-redis-proxy] memory leak

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#89]
Module: [camellia-redis-proxy]
Version: [v1.1.11]
Content: [memory leak]

-------------
- After upgrading camellia to version 1.1.11, My service got some new errors:
`i.n.u.ResourceLeakDetector:319 - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.`
- https://netty.io/wiki/reference-counted-objects.html
- I never got it before

**Comment by tasszz2k** [comment]
![image](https://user-images.githubusercontent.com/48039235/211981395-7c25ab92-06ea-46e5-9603-dda0a04041c7.png)

**Comment by caojiajun** [comment]
could you pls grep the proxy log-file with keywords `ChannelNotActive`

**Comment by tasszz2k** [comment]
> ChannelNotActive

yep, I got it
![image](https://user-images.githubusercontent.com/48039235/211986409-ac747800-8db0-4f4c-84ed-9ad8b946f437.png)

**Comment by caojiajun** [comment]
i will fix this bug in 1.1.12, maybe i will release 1.1.12 today.

**Comment by tasszz2k** [comment]
could you tell me why?

**Comment by caojiajun** [comment]
root cause：
from 1.1.8, i optimize the `BulkReply`, use `ByteBuf` instead of `byte[]`, so `ReplyEncoder` will write `ByteBuf` to client channel direct.
but if the client connection disconnect before `BulkReply` write in, the `ByteBuf` in `BulkReply` will leak, no one will call `release`.

**Comment by tasszz2k** [comment]
Hope you can fix soon
Thank you.

**Comment by tasszz2k** [comment]
> this optimize maybe rollback. i think it is very dangerous, easily trigger bugs.

please, test carefully before releasing.

**Comment by caojiajun** [comment]
> > this optimize maybe rollback. i think it is very dangerous, easily trigger bugs.
> 
> please, test carefully before releasing.

my fault

I have a performance test before 1.1.8 release. but the bug do not appear.

**Comment by caojiajun** [comment]
and in my online environment, it never appear becase the `BigKeyProxyPlugin` enabled

if you enabled `BigKeyProxyPlugin`, your case `client connection disconnect before reply` maybe will not lead to memory leak in most `commands`.

**Comment by tasszz2k** [comment]
Why is that issue fixed by "BigKeyProxyPlugin"?

**Comment by caojiajun** [comment]
> Why is that issue fixed by "BigKeyProxyPlugin"?

some commands, not all.

`GET` commnd as a example, `BigKeyProxyPlugin` will call method 'getRaw' of `BulkReply`, it makes `ByteBuf -> byte[]`

**Comment by caojiajun** [comment]
I think the optimize ideas of BulkReply through direct buf is right. 
but I need find the right way to do it.

**Comment by tasszz2k** [comment]
> > > this optimize maybe rollback. i think it is very dangerous, easily trigger bugs.
> > 
> > 
> > please, test carefully before releasing.
> 
> my fault
> 
> I have a performance test before 1.1.8 release. but the bug do not appear.

Which tool did you use for performance testing?

**Comment by caojiajun** [comment]
> > > > this optimize maybe rollback. i think it is very dangerous, easily trigger bugs.
> > > 
> > > 
> > > please, test carefully before releasing.
> > 
> > 
> > my fault
> > I have a performance test before 1.1.8 release. but the bug do not appear.
> 
> Which tool did you use for performance testing?

redis-benchmark

**Comment by caojiajun** [comment]
is this issue fixed after upgrade to `1.1.12`? @tasszz2k

**Comment by tasszz2k** [comment]
> 

yes, let me close this issue
