### ISSUE TITLE
camellia-redis-proxy 多读模式下希望支持IP和端口的健康检查，自动摘除有故障的机器。

### ISSUE THREAD

**Issue by avyou** [netease-im/camellia#95]
你好，

Module: camellia-redis-proxy
Content: 多读模式下希望支持健康检查，自动摘除有故障的机器。

`cat resource-table.json
{ 
 "type": "simple",
  "operation": {
    "read": { 
      "resources": [
        "redis://xxxxx@l@b@xxxx:15000",
        "redis://xxxxx@l@b@xxxx:15000"
      ],
      "type": "random" 
    },
    "type": "rw_separate",
    "write": {
      "resources": [
        "redis://xxxxx@l@b@192.xxx:15000",
        "redis://xxxxx@l@b@192.xxx:15000"
      ],
      "type": "multi"
    }
  }
}`

在以上配置中，希望多读下的IP列表中，支持健康检查，能够自动摘除有故障的机器，如果能支持权重调整那就更好了。如：
`    "read": { 
      "resources": [
        "redis://xxxxx@l@b@xxxx:15000 100",
        "redis://xxxxx@l@b@xxxx:15000 90"
      ],`

谢谢！

**Comment by caojiajun** [comment]
权重可以先配相同的地址多个的方式实现，直接权重值的方式改动太多，暂时先不支持

**Comment by caojiajun** [comment]
1.2.0 已经release，相关功能已经支持
